### ISSUE TITLE
Compile on Mac Os X

### ISSUE THREAD

**Issue by woytas34** [gitlem/transmission-leechermod#1]
I can't compile this under Mac Os X 10.6.3 using Xcode. Can You give me a tip what I'm doing wrong. I get a lot's of error. Please make a ready version for Os X or give me a tip how to compile under Mac Os 10.6. My e'mail is woytas34@gmail.com. Thnx!

**Comment by gitlem** [comment]
have you tried to apply the patch (in "downloads") on the official source tarball from transmissionbt.com ?
You can't compile the git repo directly, because the official transmission repo is on SVN and uses several svn:externals. I was too lazy to make it work with git, so i simply generate .patch to apply to the official source.

**Comment by woytas34** [comment]
I haven't tried because I simply don't know how to apply the patch. I downloaded latest source version of Transmission. Can You please help me to apply the patch. I have Xcode 3.2.1. I would be very greatfull

**Comment by gitlem** [comment]
Just do:
patch -p1 -i /path/to/the/patch/transmission-1.92-leechermod-0.2.patch
in the source directory

**Comment by woytas34** [comment]
Thank You very much. I apply the patch but I got 1 error    uint8_t cheatMode = tr_torrentGetCheatMode( tor );
/Users/Transmission/libtransmission/announcer.c:688: error: 'tor' undeclared (first use in this function)

**Comment by gitlem** [comment]
I'll try to fix that tomorrow..

**Comment by woytas34** [comment]
Ok thank You!

**Comment by notme123** [comment]
I got this to compile on 2.22 for osx but where are the "Cheat" options? What I did was grabbed both git and svn version then I just rsync the git version ontop of the svn then did an svn up on third-party dir for it to build.

**Comment by gitlem** [comment]
The Mac OS UI is not supported by the patch, but the web UI is. You can just right-click on a torrent and select the cheat mode from there.

**Comment by tr-cht-fx-242p** [comment]
strictly based on the 2.33 code of this repository: transmission-leechermod

SUCCESSFUL new patch and compile for 242, 242+, upcoming 250

https://github.com/tr-cht-fx-242p/transmission-leechermod/downloads

The Mac OS UI is not supported by the patch, but the web UI is. You can just right-click on a torrent and select the cheat mode from there.

**Comment by tr-cht-fx-242p** [comment]
From the clutch web client you can just right-click on a torrent and select the cheat mode from there. On the settings menu there is a new 'Advanced View' above the 'About' giving you the new 2.50 clutch web client (can't set cheat mode from here). From the advanced client click the settings menu then 'Normal View' to go back. Inspector's Information tab shows the cheat mode in normal view.
